### ISSUE TITLE
[libs/movex-react] Fix `tsc` error: `Property 'onUpdated' does not exist on type 'MovexResourceObservable<any, any>'`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#103]
# Where

`libs/movex`

# What 

When you compile the library `npx tsc -b libs/movex-react`, it throws the following error:
`Property 'onUpdated' does not exist on type 'MovexResourceObservable<any, any>'. Did you mean 'onUpdate'?`

# Why

It's a bug, and bugs need to be squashed :)

# Definition of done
- [ ] movex-react compiles `npx tsc -b libs/movex-react`
- [ ] all regression tests are passing 'yarn test'

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia  please assign this to me

**Comment by Abhishek-Mallick** [comment]
Fixed in https://github.com/movesthatmatter/movex/pull/112
