### ISSUE TITLE
[libs/movex-react] Add spec for `useMovex` hook

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#104]
# Where

`libs/movex-react/src/lib/hooks.ts`

# What

 Add a simple test for the `useMovex` hook. Here'a guide to test hooks https://www.toptal.com/react/testing-react-hooks-tutorial

# Why
Currently the hooks aren't tested at all, which means that any compiling or other errors introduced won't notify the CI, thus issues could easily be introduced.

# Definition of done
- [ ] running ` npx nx test movex-react ` will run the new test(s)
- [ ] all other tests are still passing `yarn test`

**Comment by Arol15** [comment]
@GabrielCTroia can I work on this, please?

**Comment by GabrielCTroia** [comment]
Of course! 🙌

**Comment by Arol15** [comment]
@GabrielCTroia should I create a `specs` folder in `src` and add `useMovex.spec.ts` to it or just add `useMovex.spec.ts` to the location you mentioned `libs/movex-react/src/lib/hooks.ts`? I hope it's ok to ask these clarifying questions before making a commit.

**Comment by GabrielCTroia** [comment]
HI @Arol15, thank you for your question – of course it's ok to ask!

I think it's best to create a `specs` folder next to `lib` and in it a `hooks` folder where you put the `useMovex.spec.ts`. So the final path would be `libs/movex-react/src/specs/hooks/useMovex.spec.ts`

Let me know if you have any other questions and thank you for your contribution! 🙌

**Comment by GabrielCTroia** [comment]
Closed in #132
