### ISSUE TITLE
[libs/movex-server] Disable eslint rule for `bin` file: `@typescript-eslint/no-var-requires`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#105]
# Where 

`libs/movex-server/src/bin.ts`

# What
Add the following code `/* eslint @typescript-eslint/no-var-requires: 0 */` after `#!/usr/bin/env node` line

# Why
This is a special file and imports need to written with `require`

# Definition of success
- [ ] running `npx nx lint movex-server --quiet` doesn't find errors in `libs/movex-server/src/bin.ts` file

**Comment by techemmy** [comment]
Can I take this on?

**Comment by GabrielCTroia** [comment]
Sure!

**Comment by techemmy** [comment]
I've made a PR to fix it
