### ISSUE TITLE
[libs/movex-server] Disable eslint rule for `run` file: @typescript-eslint/no-var-requires

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#106]
# Where 

`libs/movex-server/src/bin/run.ts`

# What
Add the following code `/* eslint @typescript-eslint/no-var-requires: 0 */` at the beginning of the file

# Why
This is a special file and imports need to written with `require`

# Definition of success
- [ ] running `npx nx lint movex-server --quiet` doesn't find errors in `libs/movex-server/src/bin/run.ts` file

**Comment by riteshmukim** [comment]
I would like to work on this. Can you assign it to me?

**Comment by riteshmukim** [comment]
Hey @GabrielCTroia, this has already been fixed by @techemmy

**Comment by GabrielCTroia** [comment]
Oh, thank you for bringing it up @riteshmukim! Is there any other issue you'd like to work on?

**Comment by GabrielCTroia** [comment]
Closed in #108

**Comment by riteshmukim** [comment]
I would love to work on other issues. Let me know which one should I pick

**Comment by GabrielCTroia** [comment]
You can always check the "Good First Issues with no Assignees" category 😁https://github.com/movesthatmatter/movex/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22

**Comment by GabrielCTroia** [comment]
I'm also going to create a few more shortly! 🙌
