### ISSUE TITLE
[libs/movex-core-util] Add nx runner for tsc compiler

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#117]
# Where

`libs/movex-core-util/project.json`

```json
{
   "name": "movex-core-util",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libs/movex-core-util/src",
  "projectType": "library",
  "targets": {
   "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["libs/movex-core-util/**/*.ts"]
      }
    },
    ...
  },
}

```

# What

Add the following piece of code, **in the `targets` object just above the  `lint` property:**

```json
"tsc": {
      "executor": "nx:run-commands",
      "options": {
          "commands": [
              {
                  "command": "tsc --noEmit -p libs/movex-core-util/tsconfig.lib.json"
              }
          ]
      }
    }
```

# Why

To be able to run `npx nx tsc movex-core-util` or `npx nx tsc movex-core-util --watch` and add the typescript compiler command to CI.

This will be added as a Gtihub action so every new PR will also be checked for typescript compilation errors.

# Definition of done
- [ ] can run `npx nx tsc movex-core-util`
- [ ] can run `npx nx tsc movex-core-util --watch`

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me

**Comment by Abhishek-Mallick** [comment]
Fixed: https://github.com/movesthatmatter/movex/pull/120
