### ISSUE TITLE
[project] Add npm script to `package.json`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#118]
# Where

`package.json`

# What

<img width="1167" alt="Screenshot 2023-10-12 at 2 35 28 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/0ac8b71c-4db8-417b-b99f-35e8fdcf34b4">

### Add the following script just above `build-all-libs` field.

`"tsc-all-libs": "npx nx run-many --parallel --target=tsc --projects=movex-core-util,movex,movex-server,movex-service,movex-react,movex-vue",`,

# Why
So we can compile all libs from one command

# Definition of done
- [ ] Can run `yarn tsc-all-libs`

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me

**Comment by Abhishek-Mallick** [comment]
Fixed: https://github.com/movesthatmatter/movex/pull/122
