### ISSUE TITLE
[libs/movex-core-util] Fix linting Errors in File: `ResultError.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#127]
# Where 

`libs/movex-core-util/src/lib/core-util/ResultError.ts`

# What

When you run `npx nx lint movex-core-util --quiet` you get some errors as below:

<img width="913" alt="Screenshot 2023-10-13 at 1 51 36 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/72f5acfe-190c-462f-bac2-e37dae3738c9">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass `yarn lint`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me

**Comment by Abhishek-Mallick** [comment]
Fixed: https://github.com/movesthatmatter/movex/pull/143
