### ISSUE TITLE
[libs/movex-core-util] Fix linting Errors in File: `misc.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#128]
# Where 

`libs/movex-core-util/src/lib/core-util/misc.ts`

# What

When you run `npx nx lint movex-core-util --quiet` you get some errors as below:

<img width="884" alt="Screenshot 2023-10-13 at 1 52 54 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/62d26aa6-68d6-409e-8cc2-c74e470e7a83">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass `yarn lint`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me

**Comment by KekmaTime** [comment]
@GabrielCTroia can you assign me this issue

**Comment by Abhishek-Mallick** [comment]
Fixed: https://github.com/movesthatmatter/movex/pull/142
