### ISSUE TITLE
[libs/movex-core-util] Fix linting Errors in File: `types.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#129]
# Where 

`libs/movex-core-util/src/lib/core-util/types.ts`

# What

When you run `npx nx lint movex-core-util --quiet` you get some errors as below:

<img width="797" alt="Screenshot 2023-10-13 at 1 54 04 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/02b5aa0f-f878-490f-816c-ebd6173221bd">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass `yarn lint`
- no unnecessary code is introduced

**Comment by KekmaTime** [comment]
@GabrielCTroia i would like to work on this issue

**Comment by GabrielCTroia** [comment]
Hey @KekmaTime thanks for wish to work on it, but it seems @Rounak-stha has already started on it. 

If you find any other issue I'd gladly assign it to you 🙌
