### ISSUE TITLE
[project] Install `commitizen` as a dev dependency

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#135]
# What 

Install `commitizen` as a dev dependency

run `yarn add --dev commitizen`

# Why

So it's part of the codebase and new devs don't have to install it globally

# Definition  of done
- can run `yarn commit` or `npx git-cz` without it being installed globally

**Comment by GabrielCTroia** [comment]
Thank you @paulkim26!

**Comment by paulkim26** [comment]
No problem :)
