### ISSUE TITLE
[movex-core-util] Fix linting in file `libs/movex-core-util/src/lib/core-util/ScketIOEmitter.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#136]
# Where 

`libs/movex-core-util/src/lib/core-util/ScketIOEmitter.ts`

# What 

When you run npx nx lint movex-core-util --quiet you currently get `error  Promise executor functions should not be async  no-async-promise-executor`

Removing the async operator should solve the issue

# Why
Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass <strike>`yarn lint`</strike> `npx nx lint movex-core-util --quiet`
- no unnecessary code is introduced

**Comment by AkshitMital** [comment]
Hey @GabrielCTroia , can you please assign this issue to me?

**Comment by GabrielCTroia** [comment]
Of course! 🙏

**Comment by AkshitMital** [comment]
@GabrielCTroia All other tests are passed but there is an error while running "yarn lint":
error Command "lint" not found.
<img width="1512" alt="Screenshot 2023-10-16 at 3 14 35 AM" src="https://github.com/movesthatmatter/movex/assets/116814372/bd375d5c-9a5d-4a4e-9aa8-38760a7c1bd6">

**Comment by GabrielCTroia** [comment]
Oh yeah, my bad! You can run `npx nx lint movex-core-util --quiet` this instead for now! 🙌

**Comment by AkshitMital** [comment]
Is it alright? There is no error in "libs/movex-core-util/src/lib/core-util/ScketIOEmitter.ts"

<img width="1512" alt="Screenshot 2023-10-16 at 3 36 11 AM" src="https://github.com/movesthatmatter/movex/assets/116814372/d5604fa1-8165-4b73-90bf-1c37cc3b0718">

**Comment by AkshitMital** [comment]
@GabrielCTroia My commit has been blocked. After reading the Contributing.md file again, I realized I have not signed the commit. Can you please tell how to do so and what should I do now?

**Comment by GabrielCTroia** [comment]
Hey @AkshitMital sure! Please check this https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by AkshitMital** [comment]
@GabrielCTroia I was not able to verify the old commit so I created a new branch with a verified commit and I am opening a new pull request.

**Comment by GabrielCTroia** [comment]
Close #154
