### ISSUE TITLE
[project] Duplicate the `libs/movex/Readme.md` at root

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#137]
# Context

Currently the readme for the whole repo is actually living at `libs/movex/README.md` and it has a symlink referencing it at root level `/README.md` to keep things DRY . 

This made sense in the past but no longer now, because the 2 READMEs will now serve different purposes.

The `/` Readme will represent the whole project, while the `libs/movex` one will only describe the `movex` npm library.

# What 

Remove the symlink and make an actual real copy of the movex/readme into root. 

# Definition of done 
- the symlink is gone and the root readme will be an actual hard copy of the movex readme (for now)

**Comment by jude-san** [comment]
Hi @GabrielCTroia can I take this one?

**Comment by GabrielCTroia** [comment]
Than kyou @jude-san, I just assigned it to you!

**Comment by jude-san** [comment]
thanks
