### ISSUE TITLE
[libs/movex-core-util] Fix linting Errors in File: `Logsy.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#138]
# Where 

`libs/movex-core-util/src/lib/core-util/Logsy.ts`

# What

When you run `npx nx lint movex-core-util --quiet` you get some errors as below:

<img width="832" alt="Screenshot 2023-10-14 at 1 51 44 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/4153480a-85a4-4974-a6d3-58f10a2f2e74">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass `yarn lint`
- no unnecessary code is introduced

**Comment by riteshmukim** [comment]
@GabrielCTroia  can you please assign this to me?

**Comment by GabrielCTroia** [comment]
Closed in #160
