### ISSUE TITLE
[movex-core-util] Remove unused `EmitterEventMap` interface

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#139]
# Where

`libs/movex-core-util/src/lib/core-util/EventEmitter.ts`

# What

Remove the `EmitterEventMap` on the last line

# Why 
It's not used anymore and it throws a linting error

# Definition of done
- the interface is removed EmitterEventMap

**Comment by sotiriszogos** [comment]
Hello, can I work on that?

**Comment by GabrielCTroia** [comment]
Just assigned you @sotiriszogos
