### ISSUE TITLE
[libs/movex-core-util] Fix linting Errors in File: /core-util/types.ts

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#140]
# Where

`libs/movex-core-util/src/lib/core-util/types.ts`

# What 

Running `npx nx lint movex-core-util --quiet` you get some errors as below:

<img width="781" alt="Screenshot 2023-10-14 at 1 57 54 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/7225eaeb-caf8-4a9d-b366-bcaf80760d20">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass `yarn lint`
- no unnecessary code is introduced

**Comment by riteshmukim** [comment]
@GabrielCTroia can you please assign this to me...?

**Comment by GabrielCTroia** [comment]
Closed in #161
