### ISSUE TITLE
[project] Remove the `node-18.x` from `CI` Github Action

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#149]
# Where

`.github/workflows/node.js.yml`

# What 

Remove `18.x` from the node-version 
<img width="317" alt="Screenshot 2023-10-15 at 1 08 30 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/4ec8b3a9-b018-4406-ac5a-0d951f035c81">

# Why

It's not really needed atm, it consumes resources and time. 16 should be enough for now!

# Definition of done

- the 18.x is removed from the node-versions matrix
- the action still runs

# Depends on 
- Issue #150

**Comment by AkshitMital** [comment]
@GabrielCTroia , can you please assign this issue to me?

**Comment by GabrielCTroia** [comment]
Assigned!

**Comment by GabrielCTroia** [comment]
Closed in #155
