### ISSUE TITLE
[project] Rename the Github Action: `node.js.yml`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#150]
# Where

`.github/workflows/node.js.yml`

# What 

- Rename the `name` field  from `CI` to `Tests`
- Rename the workflow file `name` from `node.js.yml` to `test.yml`

# Why

To be more in line with what is actually happening

# Definition of done

- the action still runs

# Linked with 
- Issue #149

**Comment by AkshitMital** [comment]
@GabrielCTroia , can you please assign this issue to me?

**Comment by GabrielCTroia** [comment]
Assigned @AkshitMital! 🙌

**Comment by GabrielCTroia** [comment]
Closed in #155
