### ISSUE TITLE
[movex-docs] Add lazy loader to Examples section 

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#151]
# Where

`apps/movex-docs/pages/index.mdx`

# What

Currently the `movex-docs` landing page (https://www.movex.dev/) is very slow due to the code-sandbox being very heavy and being loaded twice, for desktop and mobile!

There are other plans in the pipeline, to revamp that whole thing and not use code-sandbox at all, but for now the best would be to lazy-load those 2 iframes. 

<img width="1189" alt="Screenshot 2023-10-15 at 1 15 49 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/ac73991d-b0eb-4a3f-9945-bce086edf33e">

# Why
So the side is much faster, and can be ranked higher in google!

# Definition of done
- the mobile iframe only gets loaded on mobuile
- the desktop iframe only gets loaded on desktop
- both of them use lazy loading - meaning they only get loaded when the user scrolls down to their position

**Comment by AkshitMital** [comment]
@GabrielCTroia , can you please assign this issue to me?

**Comment by AkshitMital** [comment]
@GabrielCTroia How to run and check the index.mdx file in the browser through the terminal?

**Comment by GabrielCTroia** [comment]
Hey @AkshitMital, to start the movex-docs you can run `npx nx serve movex-docs`. 

Let me know if it worked! 🙌

**Comment by AkshitMital** [comment]
@GabrielCTroia Yeah, it is working. Thanks!!

**Comment by GabrielCTroia** [comment]
Closed in #157
