### ISSUE TITLE
[project] Add command to serve `movex-docs`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#158]
# Where

`/package.json`

# What
Add the following command to run serve `movex-docs` 

`dev-movex-docs: "npx nx serve movex-docs"`

# Why
So everyone knows how to run it

# Definition of done
- can run `yarn dev-movex-docs` to serve it

**Comment by Affanzuhaib** [comment]
@GabrielCTroia  Can you please assign this issue to me?

**Comment by AtulMinz** [comment]
@GabrielCTroia Can you please assign me this issue?

**Comment by GabrielCTroia** [comment]
Hey, so sorry @Affanzuhaib & @AtulMinz someone has already worked on this, but here are more #hacktoberfest open issues https://github.com/movesthatmatter/movex/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest, and I'll open more today! 🙌

**Comment by GabrielCTroia** [comment]
Closed in #159
