### ISSUE TITLE
[project] Add command to run the linter

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#162]
# Where

`/package.json`

# What
Add the following command to run the linter

`"lint-all-libs": "npx nx run-many --parallel --target=lint --projects=movex-core-util,movex,movex-server,movex-service,movex-react,movex-vue --quiet"`

# Why
So we can lint all the libs in one command

# Definition of done
- can run `yarn lint-all-libs` check the linter

**Comment by seog-jun** [comment]
I'd like to give it a shot!

**Comment by GabrielCTroia** [comment]
Of course @seog-jun! I just ssigned it to you 🙌

**Comment by seog-jun** [comment]
@GabrielCTroia You can close the issue
