### ISSUE TITLE
[libs/movex] Fix linting Errors in File `ConnectionToMaster.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#163]
# Where 

`libs/movex/src/lib/client/ConnectionToMaster.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:
<img width="899" alt="Screenshot 2023-10-20 at 1 17 13 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/487db6c6-1ee4-46b4-91e1-17501b7e0c7e">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
Could you please assign this to me
