### ISSUE TITLE
[libs/movex] Fix linting Errors in File `io-connection.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#164]
# Where 

`libs/movex/src/lib/io-connection/io-connection.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="907" alt="Screenshot 2023-10-20 at 1 17 41 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/fd3ae3ff-9a6c-4c9c-bf1d-cf4d1961c2c9">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by SeptAlfauzan** [comment]
Could you please assign this to me

**Comment by GabrielCTroia** [comment]
Sure @SeptAlfauzan sorry for the late reply!

**Comment by seog-jun** [comment]
@GabrielCTroia If no one is working, please assign it to me. I'll wrap up this issue.

**Comment by GabrielCTroia** [comment]
Thank you @seog-jun

**Comment by seog-jun** [comment]
@GabrielCTroia Can you review the PR? Thanks

**Comment by GabrielCTroia** [comment]
Merged it! Thank you @seog-jun
