### ISSUE TITLE
[libs/movex] Fix linting Errors in File `io-events.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#165]
# Where 

`libs/movex/src/lib/io-connection/io-events.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="899" alt="Screenshot 2023-10-20 at 1 18 32 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/e7603800-0703-407b-9c9d-6be29a8e9492">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by seog-jun** [comment]
I'd like to look into it, and could you label `hacktoberfest` on it?

**Comment by SeptAlfauzan** [comment]
Could you please assign this to me

**Comment by GabrielCTroia** [comment]
Hey @SeptAlfauzan sorry for the late reply – I'm assigning this to @seog-jun as they were first but I just assigned #164 to you! 🙏
