### ISSUE TITLE
[libs/movex] Fix linting Errors in File `MovexMasterResource.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#166]
# Where 

`libs/movex/src/lib/master/MovexMasterResource.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="894" alt="Screenshot 2023-10-20 at 1 19 58 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/155adb45-62ea-45e5-9036-c5b338ee9b2f">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me
