### ISSUE TITLE
[libs/movex] Fix linting Errors in File `MemoryMovexStore.spec.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#167]
# Where 

`libs/movex/src/lib/movex-store/MemoryMovexStore.spec.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="633" alt="Screenshot 2023-10-20 at 1 21 23 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/f54cf96e-5928-4b0a-9f18-3f36a336fc24">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
Could you please assign this to me
