### ISSUE TITLE
[libs/movex] Fix linting Errors in File `ClientMaster.match.spec.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#168]
# Where 

`libs/movex/src/specs/ClientMasterOrchestration/ClientMaster.match.spec.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="692" alt="Screenshot 2023-10-20 at 1 22 29 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/339f307d-504b-4631-8671-0ad4f15b93d1">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
Could you please assign this to me
