### ISSUE TITLE
[libs/movex] Fix linting Errors in File `ClientMaster.rps.spec.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#169]
# Where 

`libs/movex/src/specs/ClientMasterOrchestration/ClientMaster.rps.spec.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="697" alt="Screenshot 2023-10-20 at 1 23 02 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/765b8d7b-a8fe-43d4-9f95-ad6d8d98588b">

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by sloth30799** [comment]
Can u assign me this one?

**Comment by GabrielCTroia** [comment]
Of course @sloth30799! Just assigned it
