### ISSUE TITLE
[libs/movex] Fix linting errors in file `specs/Movex.spec.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#180]
# Where 

`libs/movex/src/specs/Movex.spec.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="603" alt="Screenshot 2023-10-24 at 5 40 54 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/81f06b64-26a9-4ec0-8fc6-bfc3f283c8a6">

Replace the culprit line with an import such as
 ```ts
import * as consoleGroup from 'console-group';
consoleGroup.install();
```

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Please assign this to me
