### ISSUE TITLE
[libs/movex] Fix linting errors in file `libs/movex/src/specs/MovexMasterResource.spec.ts`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#181]
# Where 

`libs/movex/src/specs/MovexMasterResource.spec.ts`

# What

When you run `npx nx lint movex --quiet` you get some errors as below:

<img width="868" alt="Screenshot 2023-10-24 at 5 43 11 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/2c1b9419-8455-48d7-842a-c401d700340f">

You can access that same file with it's absolute path `'movex-core-util'`

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex`
- all tests pass `yarn test`
- no unnecessary code is introduced

**Comment by seog-jun** [comment]
I'll take a look!

**Comment by AtulMinz** [comment]
can you please to assign it me?

**Comment by GabrielCTroia** [comment]
Hey @seog-jun, let's give @AtulMinz a chance to contribute too! 🙌

**Comment by AtulMinz** [comment]
@GabrielCTroia I have created a PR, Please review it.
