### ISSUE TITLE
[movex-react] Lower the peer dependency on react version as much as possible

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#185]
# Where

`libs/movex-react/package.json`

# What

Currently, the peerDependency is set to `react@v18.0.0`. Not only is that a fixed version but it is also too high as Movex doesn't really need version 18 and could probably go as low as 17 if not 16.

So, the task is to lower this dependency as much as possible and have it as open as possible. Ideal would be something like `^16.0.0` but this needs to be tested.

# Why
Because Movex doesn't really need version 18 and could probably go as low as 17 if not 16.

# Definition of done
- the peerDependency is set as low as possible, while still ensuring it works
- all tests pass

**Comment by AtulMinz** [comment]
Can you please assign me this issue?

**Comment by Rounak-stha** [comment]
Hey, while AtulMinz works on this issue, I have some concerns.

I would love to know how we would test the package to know the lowest version of React it can work with.
would running all the existing tests be enough?

and  I'm also confused about the version mentioned in the issue's description.
Won't adding react's version as `^16.0.0` disallow the host app to use version less or greater than 16?

**Comment by GabrielCTroia** [comment]
> Hey, while AtulMinz works on this issue, I have some concerns.
> 
> I would love to know how we would test the package to know the lowest version of React it can work with. would running all the existing tests be enough?
> 
> and I'm also confused about the version mentioned in the issue's description. Won't adding react's version as `^16.0.0` disallow the host app to use version greater than 16?

Hi @Rounak-stha you are right about the version. What I actually wanted was accept react 16.0.0 and everything above. Do you know how to specify that in ‘package.json’?!

About the tests, unfortunately just running ‘yarn test’ will not be sufficient but at the moment we don’t have tests written for ‘movex-react’ (except for 1 hook), so we need to rely on some manyal testing! 

One testing scenario would be to build the examples using each major react version since 16.

**Comment by Rounak-stha** [comment]
> What I actually wanted was accept react 16.0.0 and everything above. Do you know how to specify that in ‘package.json’?!

May be this'll work.
`>= 16.0.0`
The semver [docs](https://docs.npmjs.com/cli/v6/using-npm/semver) mentions this.

![image](https://github.com/movesthatmatter/movex/assets/66557682/368288cd-69b6-4e5e-941b-7271f6c9f32f)

**Comment by GabrielCTroia** [comment]
> > What I actually wanted was accept react 16.0.0 and everything above. Do you know how to specify that in ‘package.json’?!
> 
> May be this'll work. `>= 16.0.0` The semver [docs](https://docs.npmjs.com/cli/v6/using-npm/semver) mentions this.
> 
> ![image](https://user-images.githubusercontent.com/66557682/278943742-368288cd-69b6-4e5e-941b-7271f6c9f32f.png)

This should work!

**Comment by GabrielCTroia** [comment]
Closed in #187
