### ISSUE TITLE
[libs/movex] Fix linting errors

### ISSUE THREAD

**Issue by seog-jun** [movesthatmatter/movex#194]
## Where
`libs\movex\src\specs\resources\gameReducer.ts`
`libs\movex\src\specs\resources\gameReducerWithDerivedState.ts`
`libs\movex\src\specs\util\MockConnectionEmitter.ts`
`libs\movex\src\specs\util\orchestrator.ts`

## What
Run `npx nx lint movex --quiet` and see 6 linting problems.
![image](https://github.com/movesthatmatter/movex/assets/88434287/af7bf7d3-7a49-47df-8fa3-c2850a6d01cc)

## Definition of done
running npx nx lint movex-service --quiet will not return any more errors for this file
tsc passes npx nx tsc movex
all tests pass yarn test
no unnecessary code is introduced

**Comment by GabrielCTroia** [comment]
@seog-jun assigned! sorry for the late response
