### ISSUE TITLE
Clean up Core Types file of commented code

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#23]
## What?
File `libs/movex-core-util/src/lib/core-types.ts` has a lot of code that is commented out, like below:

<img width="663" alt="Screenshot 2023-10-05 at 6 04 21 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/3943bfc5-9acf-41ec-bdf5-4d072c8ee8c6">

Simply remove all the commented code, but make sure you leave the Documentation Comments!

## Why?

To improve clean code & readability for all developers!

**Comment by Franqsanz** [comment]
Hello @GabrielCTroia, what are the comments on the documentation?

**Comment by GabrielCTroia** [comment]
Hey @Franqsanz, by "Documentation Comments" I meant anything that is still relevant to describing what the code does. 

Like the 3rd line for example, "User Info or whatever" - this is a comment to describe code, so that should stay! Even though I would take our the "whatever" part 😅

Thanks!

**Comment by Franqsanz** [comment]
Hello @GabrielCTroia, this repository is not participating in the Hacktoberfest, you must add the Hacktoberfest topic in the repository.

**Comment by GabrielCTroia** [comment]
Hey @Franqsanz! Thanks for letting me know – I'll do it asap!

**Comment by Shefalikaushal13** [comment]
Can you please assign me this issue

**Comment by GabrielCTroia** [comment]
Sorry @Shefalikaushal13 this is actually done, but forgot to close it! 🙌
