### ISSUE TITLE
Add support for Vue

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#25]
## What

Add support for the Vue Framework. 

### Definition of Done

- a new nx library at `libs/movex-vue` in the same style as `libs/movex-react` with support for the Vue framewor

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia  Can you assign this to me

**Comment by Abhishek-Mallick** [comment]
Please have a look at https://github.com/movesthatmatter/movex/pull/109

**Comment by GabrielCTroia** [comment]
Just merged this @Abhishek-Mallick! Thank you so much.

**One last thing, could you give us a star please so we can bump the repo up the hacktoberfest ladder 🤩!**

Thank you

**Comment by GabrielCTroia** [comment]
The second part of this will be to actually implement the VUE wrappers. Would you be interested in that or should I leave it unassigned? 

No rush 🙌
