### ISSUE TITLE
Add support for Angular

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#26]
## What

Add support for the Angular framework

## Definition of done

- The new library at `libs/movex-angular` i the same style as React, supporting Angular

**Comment by JuanitaCathy** [comment]
Hey, I would like to work on this however, i need some guidance as to how to start and what to do.
Can u help?

**Comment by GabrielCTroia** [comment]
> Hey, I would like to work on this however, i need some guidance as to how to start and what to do. Can you help?

Thank you @JuanitaCathy,  and yes, of course!

So, the idea is to create another library library in the mono repo similar to `movex-react`, called `movex-angular`, with the purpose of providing the needed API so `movex` can be used inside an angular app.

For example if you're familiar with react, `movex-react` provides a set of hooks and components that wraps around movex to make react developers lives' easier. Same thing with angular, what we need is a set of components or directives that help adopting movex in an angular codebase much smoother!

You can take a lot of inspiration from `movex-react` for this!

In addition I went ahead and created a separate branch https://github.com/movesthatmatter/movex/tree/add-movex-angular, where I initialize the new `libs/movex-angular` so you don't have to worry about that anymore, just about the functionality of the library! Just branch off of the `add-movex-angular` and you should be good to go!

Let me know if you have any other questions or need any help. I'm here to support you! 🙏

**Comment by GabrielCTroia** [comment]
Hey @JuanitaCathy, how's it going with this issue? 

Just checking in! Are you still on it, do you need any help? 

Let me know if you need anything 🙌

**Comment by JuanitaCathy** [comment]
Hello!
I'm still working on it. I will let you know if i get stuck somewhere. 
Thank you for your patience :)

**Comment by GabrielCTroia** [comment]
> Hello! I'm still working on it. I will let you know if i get stuck somewhere. Thank you for your patience :)

Oh no worries, just wanted to let you know I'm here if you need me, as well as the others in the community! 🙏

**Comment by GabrielCTroia** [comment]
Closing this for now
