### ISSUE TITLE
Add a Movex Redis-Store 

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#27]
## What

Movex needs to be able to save the state data in Redis as well. 

## Why

Currently it only does so in memory using the `libs/movex/src/lib/movex-store/MemoryMovexStore.ts` but for production usages Redis is a far better solution.

## Definition of Done

- The MovexRedis implements the `libs/movex/src/lib/movex-store/MovexStore.ts` interface 
- Lives at `libs/movex/src/lib/movex-store/` at least for now
- CRUD operations tests

**Comment by riteshmukim** [comment]
Hey @GabrielCTroia, I can look into this and try it out. Can you please assign it to me?

**Comment by GabrielCTroia** [comment]
Hey @riteshmukim, thank you for taking this one too – this is a big one! I will assign myself to it too, and we can work on it together or be here to help if you need help with! 

We do have this repo https://github.com/movesthatmatter/relational-redis-store that can be useful!

Let me know your thoughts!

**Comment by GabrielCTroia** [comment]
Closing this for now
