### ISSUE TITLE
Rename `reconciliatePrivateFragments` to `applyMovexStatePatches`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#28]
## What

In this file `libs/movex/src/lib/util.ts`, rename the function "reconciliatePrivateFragments" to "applyMovexPatches"

<img width="580" alt="Screenshot 2023-10-05 at 6 32 02 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/d34b84aa-6af1-479a-a27e-c7848d2831ed">

## Why
Because it's already aliased to `applyMovexStatePatches` as in the image and this would clean up some code
<img width="563" alt="Screenshot 2023-10-05 at 6 32 51 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/41d90d27-fef6-4e31-8adb-24cb064ff597">

## Definition of done

- the function is renamed
- the alias at the bottom of the file is removed as well
- no tests fail

**Comment by tvermaashutosh** [comment]
!assign @GabrielCTroia

**Comment by FreemRL** [comment]
Hi I created a PR for this issue (#35)

**Comment by GabrielCTroia** [comment]
Thank you @FreemRL! Will check shortly
