### ISSUE TITLE
Clean up `client/Movex.ts` of comments

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#29]
## What

For this file `libs/movex/src/lib/client/Movex.ts`, remove the commented code inside the class as in the below image:
<img width="902" alt="Screenshot 2023-10-05 at 6 35 50 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/590c45b5-fa29-417b-93aa-2f49ee330ff4">

## Why

To improve readablity

## Definition of done
- the commented code is removed
- the commented docs are left

**Comment by Rhythm-08** [comment]
Hi, I would like to work on it

**Comment by FreemRL** [comment]
Hey I created a PR for this :) (#34)
