### ISSUE TITLE
Use a smaller object hashing lib/function

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#30]
# What

Currently we use the [object-hash](https://www.npmjs.com/package/object-hash) library to hash the state object and get an accurate hash/token both on the client and the server (node).

This is a very important feature that sits at the core of movex - being able get a hash/token of current state both on the client and the server, which makes the state synchronization possible with minimum data sent over the wire and minimum trips. For more info see https://www.movex.dev/docs/how/state_synchronization.

# Why 

To reduce the library size!

The problem at the moment with object-hash is that it's too big, making for 17.5% of the whole movex library. That is party because we import the whole object-hash but only use the md5 function.

<img width="1573" alt="Screenshot 2023-10-05 at 6 48 37 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/4f2b3343-a78b-4157-b907-70aa29c3ffe5">
Source: https://bundlephobia.com/package/movex@0.1.2

# Definition of done

- start using a different hashing/md5-ing library or add the hashing function to the library
- VERY IMPORTANT: the resulted hash/token is the same when run in the browser AND on the server (node)
- All tests are passing `yarn test`
- The library decreased in size

**Comment by Ekep-Obasi** [comment]
@GabrielCTroia
We could directly import 
import { MD5 } from 'object-hash';

**Comment by Ekep-Obasi** [comment]
Done @GabrielCTroia 

Hacktoberfest ! 🎉
