### ISSUE TITLE
Remove the "movex/tools/resourceFile.ts"

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#31]
# What

The file `libs/movex/src/lib/tools/resourceFile.ts` isn't used anymore and can be safely removed!

# Why
Readability

# Definition of done
 - file is removed
 - all tests are passing `yarn test`

**Comment by tvermaashutosh** [comment]
!assign @GabrielCTroia

**Comment by GabrielCTroia** [comment]
Will check shortly! Thank you @tvermaashutosh

**Comment by GabrielCTroia** [comment]
See the PR!

**Comment by GabrielCTroia** [comment]
Sure!
