### ISSUE TITLE
[libs/movex-react] Remove self referencing absolute imports 

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#38]
# Where

`/libs/movex-react`

# What

There are a few imports that are directly referencing the absolute "movex-react" path (i.e. from node_modules) instead of importing from a relative path, since it's within it's directory!

See the culprit files here:

<img width="456" alt="Screenshot 2023-10-06 at 6 57 13 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/29ae9f56-6861-406f-92c6-fd6af791e950">

# Why
This is not ideal because it can create more importing issues down the road. It's also not necessary!

# Definition of done

- All the absolute imports aka `import { my_file } from 'movex-react'` is changed to `import { my_file } from './path/to/my_file'`
- Note, these only refers to imports from 'movex-react' not any of the other libraries such as 'movex', 'movex-core-util', etc.

**Comment by ikunal-04** [comment]
Hey @GabrielCTroia can you assign me this issue?

**Comment by GabrielCTroia** [comment]
Sure!
