### ISSUE TITLE
[Feedback Request] What do you understand from the "What is Movex" Diagram?

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#40]
# Why
Movex is a new tool, using a set of ideas and principle that are a bit out of common – and because of that, I am constantly trying to see if newcomers are understanding what Movex is and does!

# What 

This diagram tries to explain what movex is and how it works.

<img width="882" alt="Screenshot 2023-10-06 at 7 16 58 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/5b80af79-3d57-4072-87c4-172bd198b544">

- What do you understand from it?
- How does Movex work?
- What can you improve

Thank you 1000🙏

**Comment by Ankitv003** [comment]
Hey Gabriel, what help particularly do you want in this issue and how can i contribute ? 
P.s- It would be my first Pr for hacktoberfest , i am new to open source.
Should i create an markdown file explaining the answer to your questions or should i answer here in comments?

**Comment by GabrielCTroia** [comment]
Hi @Ankitv003 thank you so much for contributing to this! A comment here would be great to start with, and then those can be applied in the docs or image themselves later on!

Thank you 🙏

**Comment by GabrielCTroia** [comment]
Closing
