### ISSUE TITLE
[Feedback Request] What do you understand from the "How Movex Works" Docs section? 

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#41]
# Why
Movex is a new tool, using a set of ideas and principle that are a bit out of common – and because of that, I am constantly trying to see if newcomers are understanding what Movex is and does!

# What
Please navigate to  https://www.movex.dev/docs/how and give your input on the following questions

- Does it make sense to you?
- What do you understand from it?
- Does the diagram tell the full picture?
- How would you improve the diagram?
- Do you have any suggestions for improving the message?

Thank you 🙏

**Comment by Shefalikaushal13** [comment]
Can you please assign me this issue?

**Comment by GabrielCTroia** [comment]
Thank you for taking this important issue @Shefalikaushal13! 🙌

**Comment by GabrielCTroia** [comment]
Closing
