### ISSUE TITLE
[libs/movex] Remove unused file - `LocalStorageMovexStore`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#44]
# Where

`libs/movex/src/lib/movex-store/LocalStorageMovexStore.ts`

# What

Remove this file and any possible references to it

# Why 

Readability 

# Definition of deon
- [ ] the file is removeed
- [ ] all the tests are passing `yarn test`

**Comment by WangGithub0** [comment]
Hi @GabrielCTroia , could I work on this issue? thanks

**Comment by AbhigyaKrishna** [comment]
Hi @GabrielCTroia, can you assign me this issue?

**Comment by GabrielCTroia** [comment]
Hey, @AbhigyaKrishna I would, but I just realized @WangGithub0 asked as well, and I missed his comment.

I would wait to see if he still wants to work on it, and if not I'll gladly assign it to you! 

In the meantime, @AbhigyaKrishna we have bunch of https://github.com/movesthatmatter/movex/labels/good%20first%20issue, and I'll add more tomorrow! 

---

@WangGithub0 I'm sorry, I missed your comment - do you still want to work on it?

**Comment by GabrielCTroia** [comment]
Hey, @AbhigyaKrishna, it seems @WangGithub0 is not responding. I will assign this to you for now! 

Thank you!

**Comment by WangGithub0** [comment]
I came first and today is thanks giving day, I stay with my family whole day!

**Comment by GabrielCTroia** [comment]
Oh, sorry @WangGithub0! I didn't know, so do you still want to work on this?

**Comment by WangGithub0** [comment]
yea, thanks a lot

**Comment by GabrielCTroia** [comment]
You're welcome @WangGithub0.

@AbhigyaKrishna sorry for the confusion, I will re-assign this to @WangGithub0 as he was the first! 

Let me know if you want me to suggest another issue for you.
