### ISSUE TITLE
[libs/movex] Add Specs to the MemoryMovexStore Specs to test the "Delete" functionality in CRUD

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#45]
# Where

`libs/movex/src/lib/movex-store/MemoryMovexStore.spec.ts`

# What 

Add tests to assert the "Delete" functionality - the `remove()` method

# Why
To ensure the store works correctly

# Definition of done
- it tests valid item deletion
- it tests invalid item deletion (i.e. inexistent item)
- tests a newly created item deletion
- tests a newly updated item deletion
- tests a newly delete item deletion
- all other tests are still passing

**Comment by vishalda** [comment]
Hi @GabrielCTroia, I would like to work on this issue.

**Comment by GabrielCTroia** [comment]
And it shall be yours! 🙏 Thank you

**Comment by GabrielCTroia** [comment]
Closed in #79
