### ISSUE TITLE
[libs/movex] Remove the `getReducerApplicator` method

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#48]
# Where 

`libs/movex/src/lib/tools/dispatch.ts`

# What

The `getReducerApplicator` function isn't used anymore, and can be removed!

# Why

To reduce file size and improve readability

# Definition of done
- the method isn't there anymore
- all the tests are passing `yarn test`

**Comment by FreemRL** [comment]
Hi again ^^ I created a PR for this (#49)
