### ISSUE TITLE
[libs/movex] Remove unused types

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#55]
# Where

`libs/movex/src/lib/core-types.ts`

# What

Remove the commented code and the unused type `MovexState` as well as the import `MovexReducer`!

<img width="432" alt="Screenshot 2023-10-07 at 5 32 22 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/9b75a50f-f606-4e22-8426-dcae64c380c0">

# Why 
Readablity

# Definition of done

- The unused code is gone
- The comments are gone
- All tests keep passing

**Comment by khushi-rastogi** [comment]
i want to contribute kindly assign this to me

**Comment by GabrielCTroia** [comment]
> i want to contribute kindly assign this to me

Hey @khushi-rastogi, this is already taken care by @igorwessel, but here's a list of other issues we can use your help with https://github.com/movesthatmatter/movex/labels/hacktoberfest!

Thank you so much 🙏
