### ISSUE TITLE
[libs/movex] Remove unused initializer

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#59]
# Where

`libs/movex/src/lib/client/init.ts`

# What

Can safely remove the `initMovexWithLocalMaster` function as it isn't used anymore, as well as the few commented lines above, starting with line `59` in the screenshot below:

<img width="685" alt="Screenshot 2023-10-08 at 2 02 49 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/d44be18e-8344-42ea-8f43-366112a08e1a">

# Why

To increase readability and decrease file size.

# Definition of done

- the `initMovexWithLocalMaster`
- the commented code are removed (not the comments in the other function)
- any unused imports in the file are also removed

**Comment by Abhishek-Mallick** [comment]
Can you please assign this to me

**Comment by GabrielCTroia** [comment]
> Can you please assign this to me

Assigned! Thank you

**Comment by Abhishek-Mallick** [comment]
Please review PR: https://github.com/movesthatmatter/movex/pull/65
