### ISSUE TITLE
[libs/movex] Remove "applyAction" method from MovexResourceObservable

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#60]
# Where 
`libs/movex/src/lib/client/MovexResourceObservable.ts`

# What 

Remove the unused `applyAction`

<img width="804" alt="Screenshot 2023-10-08 at 2 07 13 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/0caa0d50-3569-43b5-b7be-44377207ce6c">

# Why

- Readability and decrease size

# Definition of done

- the function is gone
- all tests are still passing `yarn test`

**Comment by FreemRL** [comment]
PR created ^^ (#64)
