### ISSUE TITLE
[libs/movex] Remove commented out test in `MovexClientResourceObservable.spec`

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#61]
# Where

`libs/movex/src/specs/MovexClientResourceObservable.spec.ts`

# What

Remove the commented out spec for the now deprecated `applyAction()`
<img width="907" alt="Screenshot 2023-10-08 at 2 09 56 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/648fd741-35f8-4380-9c3c-86d047f07bf5">

# Why

Readability 

# Definition of done
- the commented code is removed
- no other test is touched
- all tests keep passing `yarn test`

**Comment by FreemRL** [comment]
Hey created a PR for this :) (#63)

**Comment by GabrielCTroia** [comment]
Merged!
