### ISSUE TITLE
[libs/movex] Test the MovexResourceObservable `destroy` functionality 

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#62]
# Where

`libs/movex/src/specs/MovexClientResourceObservable.spec.ts`

# What

Add specs to test that the Observable destroy correctly. 

<img width="519" alt="Screenshot 2023-10-08 at 2 12 02 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/903291dd-4c45-4d89-9ad0-8c3fe2ed3dea">

# Why

This functionality is really important because it's called when the Observable is not used anymore in order to clean the update subscriptions

# Definition of done
- At least one test checking that after `destroy()` is called, the listeners to `MovexResourceObservable.onUpdate()` don't get called anymore
- All other tests are passing `yarn test`

**Comment by vinayakhegde1** [comment]
@GabrielCTroia What testing tools or packages should be installed for this. Sorry I'm new I wanted to know what exactly I have to do after adding a new spec run yarn test or I have to install any packages before that

**Comment by GabrielCTroia** [comment]
Hey @vinayakhegde1, no worries! Thank you for asking!

You don't need to install anything, jest is already installed and can be used by running `yarn test` or to watch `yarn test --watch`

**Comment by vinayakhegde1** [comment]
@GabrielCTroia Thanks! I'll give it a try I don't know if can do it perfectly or not

**Comment by GabrielCTroia** [comment]
> @GabrielCTroia Thanks! I'll give it a try I don't know if can do it perfectly or not

No worries about perfection! I'm here to help as well. Getting something started is half the battle - we can then iterate on it together!

Thank you!🙏

**Comment by vinayakhegde1** [comment]
@GabrielCTroia 
![image](https://github.com/movesthatmatter/movex/assets/73926849/7ceb3960-02e5-415e-bdae-5025d94ef4e5)
I don't what is wrong in this but i'm getting 1 test pass failed
