### ISSUE TITLE
[libs/movex] Remove comments in file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#66]
# Where

`libs/movex/src/lib/client/MovexResourceObservable.ts`

# What

Remove the commented code at line 97 to 103 as it's not needed anymore.

<img width="923" alt="Screenshot 2023-10-09 at 3 52 41 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/ea7c2709-81a2-4aa3-bfdb-cf9d21908bf5">

# Why
Readability 

# Definition of done
- the commented code is out
- all the other code and comments are left in
- all tests are passing `yarn test`

**Comment by UzairNoman** [comment]
Hi @GabrielCTroia, I would like to work on this issue. Can you please assign this to me :)

**Comment by GabrielCTroia** [comment]
I just assigned you! Thank you
