### ISSUE TITLE
[apps/movex-docs] Clean up `Hero` file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#69]
# Where

`apps/movex-docs/modules/home/Hero.tsx`

# What

This file seems to have a lot of code smells, such as:
- commented code
- unused imports
- unused code (aka currentTheme, darkColors)

# Why

Readability & file size

# Definition of done 
- [ ] the commented code are gone
- [ ] the unused code is removed
- [ ] the unused imports are removed
- [ ] tests still pass `yarn test`

**Comment by VishalMyla** [comment]
Can you assign this issue to me ?

**Comment by GabrielCTroia** [comment]
Of course @VishalMyla! Thank you
