### ISSUE TITLE
[apps/movex-docs] Clean up `HeroSubText` file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#70]
# Where

`apps/movex-docs/modules/home/HeroSubText.tsx`

# What

Clean up the commented out code, such as:
<img width="1220" alt="Screenshot 2023-10-09 at 4 53 14 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/df0ffb08-dda7-4091-9af3-1b8e940a7efc">

# Why 
Readability

# Definition of done
- [ ] comments aren't there anymore
- [ ] tests are still passing

**Comment by pranav-jadhav** [comment]
Please assign me this issue

**Comment by GabrielCTroia** [comment]
Sorry @pranav-jadhav, @Ekep-Obasi already worked on this! Here's a list of other good first issues https://github.com/movesthatmatter/movex/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest to choose from!

Thank you for your interest, and please give us a star! 🙏
