### ISSUE TITLE
[apps/movex-demo] Build a tic-tac-toe multiplayer game in Movex

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#71]
# Where

`apps/movex-demo`

# What

You have the freedom to design the game anyway you like - you can take inspiration from the Rock Paper Scissors (https://codesandbox.io/s/rps-demo-x877yl) game, but it needs to satisfy the following:
- uses Movex (obviously)
- it's build inside the `apps/movex-demo` app. Just use another page to show it
- works locally as well as remote

# Why

To learn how to do it and to have a demo of multiplayer tic-tac-toe using movex, showing that the multiplayer part is really easy.

**Comment by Ekep-Obasi** [comment]
@GabrielCTroia  
Can you assign this issue to me ?

**Comment by Ekep-Obasi** [comment]
Thank you! @GabrielCTroia 
On it 🙏🏽

**Comment by GabrielCTroia** [comment]
Hey @Ekep-Obasi any luck with this? Do you need any help?

**Comment by Ekep-Obasi** [comment]
Hi @GabrielCTroia 
Yeah I did face some challanges running the demo projects

**Comment by GabrielCTroia** [comment]
Closing for now
