### ISSUE TITLE
[apps/movex-demo] Typo in the documentation

### ISSUE THREAD

**Issue by Ekep-Obasi** [movesthatmatter/movex#73]
## Where

`movex\apps\movex-docs\pages\docs\how.mdx`

# What

![movex-typo-error](https://github.com/movesthatmatter/movex/assets/117433403/f794227c-3cb3-4d30-b82f-abb4de26e246)

# Definition of done 

- [ ] Correct spelling 
- [ ] tests are still passing

**Comment by GabrielCTroia** [comment]
Thank you for opening this issue up @Ekep-Obasi! Really appreciate it 🙏
