### ISSUE TITLE
[libs/movex-core-util] Refactor Observable to implement IObservable

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#77]
# Where 

`libs/movex-core-util/src/lib/core-util/Observable.ts`

# What 

Currently there is an IObservable interface as well as a class Observable. 

The Observable should implement the IObservable exactly, but currently it doesn't!

<img width="449" alt="Screenshot 2023-10-09 at 8 31 43 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/86c43161-fc23-41f7-89cd-9da4bca31e29">

# Why
To remove confusion

# Definition of done
- Observable class implements IObservable interface correctly
- all tests pass `yarn test`

**Comment by MightyM17** [comment]
So just adding the implements to the Observable class (and fixing the functions)?

**Comment by GabrielCTroia** [comment]
Yes, and fixing the discrepancy between the naming of `onUpdated` method, which most likely will trigger some tests to fail or compile issues. 

Thank you for looking into it!

**Comment by MightyM17** [comment]
Alright will do :D

**Comment by GabrielCTroia** [comment]
Thank you! I assigned you to it! 🙏

Let me know if you have any other questions or need my help!
