### ISSUE TITLE
[apps/movex-docs] Add favicon to Next app

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#83]
# Where 

`apps/movex-docs`

# What

Add this logo `https://github.com/movesthatmatter/movex/blob/main/art/x_logo_a.png` as a fav icon for the movex-docs next app.

You will need to create new icons probably using something like https://favicon.io/ or similar.

# Why

Because currently it's blank

# Definition of done
- [ ] the fav icon works on all platforms (desktop, mobile)
- [ ] all tests pass `yarn test`

**Comment by chanon-mike** [comment]
I would like to work on this

**Comment by GabrielCTroia** [comment]
Thank you @chanon-mike I've assigned it to you!
