### ISSUE TITLE
[apps/movex] Remove commented out code

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#84]
# Where

`libs/movex/src/lib/master/index.ts`

# What
<img width="413" alt="Screenshot 2023-10-10 at 5 22 59 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/a2f72df7-6065-49ee-a640-79ebe586f0fe">

# Why 
Readability

# Definition of done
- the 2 lines of code aren't there any more
- all tests continue to pass `yarn test`

**Comment by techemmy** [comment]
can i get assigned to fix this issue?

**Comment by GabrielCTroia** [comment]
Thank you @techemmy for fixing this!
