### ISSUE TITLE
[libs/movex] Clean up code in `MovexMasterServer` file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#85]
# Where

`libs/movex/src/lib/master/MovexMasterServer.ts`

# What

Remove this unused commented out code

<img width="1111" alt="Screenshot 2023-10-10 at 5 26 45 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/611bf225-6606-4f9f-96c6-09871be34367">

# Why
Readability

# Definition of done
- the comments are gone
- all tests are still passing `yarn test`

**Comment by rabroldan** [comment]
hi there can i take this one?

**Comment by GabrielCTroia** [comment]
Yessir! Just assigned it to you 🚀

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Is this issue still up for a grab?

**Comment by GabrielCTroia** [comment]
Hey @Abhishek-Mallick, I think so!

@rabroldan any updates on this?

I will assign it to you too @Abhishek-Mallick in the meantime! 🙌

**Comment by rabroldan** [comment]
Hey there yeah this was already merged and finished Please see (https://github.com/movesthatmatter/movex/pull/107)

**Comment by GabrielCTroia** [comment]
Oh awesome, thank you @rabroldan! Will close then! 🙌
