### ISSUE TITLE
[libs/movex] Refactor Generic `TState extends any` in `ConnectionToClient` file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#94]
# Where

`libs/movex/src/lib/master/ConnectionToClient.ts`

# What

Take out the `any` from `TState extends any` since it doesn't add any benefit
 
<img width="508" alt="Screenshot 2023-10-11 at 12 27 04 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/5b7c023e-1030-439c-96ab-b281996170d4">

# Why

Readabilty

# Definition of done
- [ ] `TState` doesn't extend `any` anymore
- [ ] All tests continue to pass `yarn test`

**Comment by AbhigyaKrishna** [comment]
Assign this to me
