### ISSUE TITLE
[libs/movex] Refactor Generic `TState` extends any in `ConnectionToMaster` file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#95]
# Where

`libs/movex/src/lib/client/ConnectionToMaster.ts`

# What

Take out the `any` from `TState extends any` since it doesn't add any benefit
 
<img width="348" alt="Screenshot 2023-10-11 at 12 30 02 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/d8a56b3b-2c0e-4a5c-9a29-f58fd8667741">

# Why

Readabilty

# Definition of done
- [ ] `TState` doesn't extend `any` anymore
- [ ] All tests continue to pass `yarn test`

**Comment by AbhigyaKrishna** [comment]
Assign this to me

**Comment by GabrielCTroia** [comment]
Hey @AbhigyaKrishna, thank you for your interest. Is it ok if we give other first contributors a chance as well? 🙏

If no one shows up I will gladly assign it to you 🫶

**Comment by AbhigyaKrishna** [comment]
Sure thing

**Comment by farhanalws4u** [comment]
Hi @GabrielCTroia , Can i work on this ?

**Comment by GabrielCTroia** [comment]
> Hi @GabrielCTroia , Can i work on this ?

Sure thing @farhanalws4u! It's yours

**Comment by GabrielCTroia** [comment]
Hey @farhanalws4u did you get a chance to work on this or do you need any help?

**Comment by farhanalws4u** [comment]
sorry i couldn't respond on time because i was busy with my exams, actually i had changed the type but when i was installing the dependencies to run test cases , it was showing some error that i could not resolved. So if its ok to raise PR without installing dependencies and running test cases, i can raise pr

**Comment by GabrielCTroia** [comment]
Sure @farhanalws4u no worries. You can open a PR. Also what is the error you're getting? Maybe you need to pull from the latest `main`?!

Let me know if you need more help 🙌

**Comment by farhanalws4u** [comment]
hey @GabrielCTroia thanks for your response, I think the issue was already fixed by someone four days ago that I didn't notice before, and now I am not getting those errors as well. So I don't think I should raise PR for this.

**Comment by farhanalws4u** [comment]
Also, I want to understand project structure, workflow, and everything for future contributions, can you guide me on where I can start or something that can help me?

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia as this issue is not getting picked by anyone for this moment can you assign this to me

**Comment by GabrielCTroia** [comment]
> Reference

Yes of course! Thank you for your interest @farhanalws4u! I'd say the best place to start is the [Get Started](https://www.movex.dev/docs/overview/get_started) Article in our Docs, and then go from there.

For the workflow you can check our [CONTRIBUTING GUIDE](https://github.com/movesthatmatter/movex/blob/main/CONTRIBUTING.md) and [Code Of Conduct](https://github.com/movesthatmatter/movex/blob/main/CODE_OF_CONDUCT.md)

### As for the codebase here's a quick summary:
The project is structured as a monorepo, which means all of the libraries are part of the same codebase. This allows for easy code sharing between libraries and keeping things organized well.

We have a bunch of libraries that together make Movex, found at `libs/`:
- **movex** - this is the core of Movex and takes care of the client/master interaction, the protocols used and most of the important logic
- **movex-core-util** - contains logic and utility functions that are used in **movex** as well as other libs
- **movex-react** - is a wrapper around Movex to support react out of the box
- **movex-examples** - this is deprecated 
- **movex-service** - is the cli tool that serves movex for dev or production
- **movex-server** - is an Express server used by **movex-service** to serve the application in dev or production

We also have a few apps, found at `/apps`
- **movex-docs** - The docs website built on [Nextra.js](https://nextra.site/)
- **movex-demo** - An upcoming website for showcasing what can be built with Movex. Built with Next.js

Additionally, you can ask more questions and talk to more people in our community in our Discord channel https://discord.gg/N8k447EmBh

Hope this helps, and thank you for the question 🙏🙌

**Comment by GabrielCTroia** [comment]
@Abhishek-Mallick, this seems to be already fixed now, so I'm going to close this issue altogether!

**Comment by farhanalws4u** [comment]
> > Reference
> 
> Yes of course! Thank you for your interest @farhanalws4u!
> 
> I'd say the best place to start is the [Get Started](https://www.movex.dev/docs/overview/get_started) Article in our Docs, and then go from there.
> 
> For the **workflow** you can check our [CONTRIBUTING GUIDE](https://github.com/movesthatmatter/movex/blob/main/CONTRIBUTING.md) and [Code Of Conduct](https://github.com/movesthatmatter/movex/blob/main/CODE_OF_CONDUCT.md)
> 
> #### As for the codebase here's a quick summary:
> The project is structured as a monorepo, which means all of the libraries are part of the same codebase. This allows for easy code sharing between libraries and keeping things organized well.
> 
> We have a bunch of libraries that together make Movex, found at `libs/`:
> 
> * **movex** - this is the core of Movex and takes care of the client/master interaction, the protocols used and most of the important logic
> * **movex-core-util** - contains logic and utility functions that are used in **movex** as well as other libs
> * **movex-react** - is a wrapper around Movex to support react out of the box
> * **movex-examples** - this is deprecated
> * **movex-service** - is the cli tool that serves movex for dev or production
> * **movex-server** - is an Express server used by **movex-service** to serve the application in dev or production
> 
> We also have a few apps, found at `/apps`
> 
> * **movex-docs** - The docs website built on [Nextra.js](https://nextra.site/)
> * **movex-demo** - An upcoming website for showcasing what can be built with Movex. Built with Next.js
> 
> Additionally, you can ask more questions and talk to more people in our community in our [Discord](https://discord.gg/N8k447EmBh).
> 
> Hope this helps, and thank you for the question 🙏🙌

Thanks @GabrielCTroia, it's really helpful.
