### ISSUE TITLE
[libs/movex] Refactor Generic `TState` extends any in `ConnectionToMasterResource` file

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#96]
# Where

`libs/movex/src/lib/client/ConnectionToMaster.ts`

# What

Take out the `any` from `TState extends any` since it doesn't add any benefit
 
<img width="516" alt="Screenshot 2023-10-11 at 12 32 58 PM" src="https://github.com/movesthatmatter/movex/assets/2099521/e738c843-5e5f-401a-b6b8-beacdb3b57ec">

# Why

Readabilty

# Definition of done
- [ ] `TState` doesn't extend `any` anymore
- [ ] All tests continue to pass `yarn test`

**Comment by AbhigyaKrishna** [comment]
Assign this to me

**Comment by navyarathore** [comment]
Hey! you can assign it to me.

**Comment by GabrielCTroia** [comment]
> Hey! you can assign it to me.

Assigned!
