### ISSUE TITLE
[libs/movex] Add nx runner for `tsc` compiler

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#98]
# Where

`libs/movex/project.json`

```json
{
  "name": "movex",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libs/movex/src",
  "projectType": "library",
  "targets": {
    "build": {
      "executor": "@nrwl/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
      ...
      }
    },
    ...
  },
}

```

# What

Add the following piece of code, **in the `targets` object just above the  `build` property:**

```json
"tsc": {
      "executor": "nx:run-commands",
      "options": {
          "commands": [
              {
                  "command": "tsc --noEmit -p libs/movex/tsconfig.lib.json"
              }
          ]
      }
    }
```

# Why

To be able to run `npx nx tsc movex ` or `npx nx tsc movex --watch` and add the typescript compiler command to CI.

This will be added as a Gtihub action so every new PR will also be checked for typescript compilation errors.

# Definition of done
- [ ] can run `npx nx tsc movex`
- [ ] can run `npx nx tsc movex --watch`

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me

**Comment by Abhishek-Mallick** [comment]
Fixed: https://github.com/movesthatmatter/movex/pull/115
